// GENERATED by scripts/specimen/sculpture.py from the Blender plate (scripts/specimen/fulgurite.py --variant plate)
// and the record it was rendered from. Do not edit: run scripts/specimen/make-sculpture.sh.
// Plate pixels are measured from the plate's top left; the camera is the plate's own, in three.js coordinates.

export const SCULPTURE = {
  "plate": {
    "width": 2000,
    "height": 4000,
    "sha": "f4ac371c4ca2",
    "bbox": [
      427,
      198,
      1222,
      3560
    ]
  },
  "camera": {
    "position": [
      -15.917283,
      -6.479468,
      22.056185
    ],
    "target": [
      -0.430456,
      -6.479468,
      -0.580848
    ],
    "vfov": 30.0
  },
  "specimen": {
    "generatedAt": "2026-09-27T21:46:06.104Z",
    "sha256": "5b0e39ab7289d3ac0f172bc86d52201d26fade167e820062110fe25dd7ae76dd",
    "tubes": 170,
    "beads": 697
  },
  "samples": 768,
  "surface": 223.2,
  "tip": 3491.0,
  "descent": [
    {
      "id": "2023-2024",
      "from": 223.2,
      "to": 499.5
    },
    {
      "id": "2025",
      "from": 499.5,
      "to": 1388.0
    },
    {
      "id": "2025-10-2026-03",
      "from": 1388.0,
      "to": 1835.4
    },
    {
      "id": "2026-04-2026-07",
      "from": 1835.4,
      "to": 2429.8
    },
    {
      "id": "2026-08",
      "from": 2429.8,
      "to": 2886.0
    },
    {
      "id": "2026-09",
      "from": 2886.0,
      "to": 3491.0
    }
  ],
  "windows": {
    "2023-2024": [
      387,
      0,
      1302,
      814
    ],
    "2025": [
      387,
      463,
      1302,
      1184
    ],
    "2025-10-2026-03": [
      387,
      1204,
      1302,
      814
    ],
    "2026-04-2026-07": [
      387,
      1723,
      1302,
      814
    ],
    "2026-08": [
      387,
      2244,
      1302,
      814
    ],
    "2026-09": [
      387,
      2782,
      1302,
      814
    ],
    "tip": [
      387,
      2954,
      1302,
      814
    ]
  },
  "files": {
    "plate-450.webp": {
      "w": 450,
      "h": 900,
      "bytes": 49040,
      "q": 80
    },
    "plate-640.webp": {
      "w": 640,
      "h": 1280,
      "bytes": 85664,
      "q": 80
    },
    "plate-900.webp": {
      "w": 900,
      "h": 1800,
      "bytes": 146524,
      "q": 80
    },
    "plate-1400.webp": {
      "w": 1400,
      "h": 2800,
      "bytes": 289316,
      "q": 80
    },
    "plate-2000.webp": {
      "w": 2000,
      "h": 4000,
      "bytes": 528280,
      "q": 80
    },
    "era-2023-2024-800.webp": {
      "w": 800,
      "h": 500,
      "bytes": 44688,
      "q": 80
    },
    "era-2023-2024-1320.webp": {
      "w": 1302,
      "h": 814,
      "bytes": 94978,
      "q": 80
    },
    "era-2025-800.webp": {
      "w": 800,
      "h": 727,
      "bytes": 99000,
      "q": 80
    },
    "era-2025-1320.webp": {
      "w": 1302,
      "h": 1184,
      "bytes": 208250,
      "q": 80
    },
    "era-2025-10-2026-03-800.webp": {
      "w": 800,
      "h": 500,
      "bytes": 65126,
      "q": 80
    },
    "era-2025-10-2026-03-1320.webp": {
      "w": 1302,
      "h": 814,
      "bytes": 134298,
      "q": 80
    },
    "era-2026-04-2026-07-800.webp": {
      "w": 800,
      "h": 500,
      "bytes": 66240,
      "q": 80
    },
    "era-2026-04-2026-07-1320.webp": {
      "w": 1302,
      "h": 814,
      "bytes": 133706,
      "q": 80
    },
    "era-2026-08-800.webp": {
      "w": 800,
      "h": 500,
      "bytes": 41072,
      "q": 80
    },
    "era-2026-08-1320.webp": {
      "w": 1302,
      "h": 814,
      "bytes": 85340,
      "q": 80
    },
    "era-2026-09-800.webp": {
      "w": 800,
      "h": 500,
      "bytes": 23674,
      "q": 80
    },
    "era-2026-09-1320.webp": {
      "w": 1302,
      "h": 814,
      "bytes": 47756,
      "q": 80
    },
    "era-tip-800.webp": {
      "w": 800,
      "h": 500,
      "bytes": 18786,
      "q": 80
    },
    "era-tip-1320.webp": {
      "w": 1302,
      "h": 814,
      "bytes": 36938,
      "q": 80
    }
  }
} as const;
