// GENERATED FILE. Do not edit by hand.
//
//   npm run pack          regenerate
//   npm run verify:ask    fails if this file has drifted from lib/ask/pack.ts
//
// Written by scripts/build-pack.mjs from lib/ask/pack.ts, which reads the
// content collections. Every line below traces to content/**; nothing here was
// typed. Kept as an array of lines so a review diff shows which section of the
// site moved, not one changed megabyte.

/** sha256 of the pack text, for the drift check and the health payload. */
export const GROUNDING_PACK_SHA256 = "135b752af3b8ffe01f649236d48b9827e244a3a46991e1caab7906f9d2d1a293";

export const GROUNDING_PACK = [
  "# James Brady — site content pack",
  "",
  "Every fact the assistant may state lives below. James Brady builds AI systems that show their work. One person, operating at fleet scale — documenting what actually works.",
  "Canonical host: https://www.jamesbrady.org. Location: Lehi, UT. Contact: james@utlyze.com.",
  "",
  "How to read this pack:",
  "- Each section starts with the URL that section came from. Cite that URL.",
  "- `[pending]` marks a fact James has not supplied yet. Say the fact is not published; never fill the hole.",
  "- Client work is anonymized on purpose. No client is named here, so no client can be named in an answer.",
  "- Content © James Brady. Cite the source URL. Figures are computed at build; method is stated on-page.",
  "",
  "## Pages",
  "",
  "### James Brady — builds AI systems that show their work",
  "Source: https://www.jamesbrady.org/",
  "What it covers: James Brady builds AI systems that show their work, and every figure on this site is computed from its source at build rather than typed by hand.",
  "",
  "### Work",
  "Source: https://www.jamesbrady.org/work",
  "What it covers: The work index lists products, open-source projects, client work and experiments, filtered in the browser with a count read from what is on screen.",
  "",
  "### Theories",
  "Source: https://www.jamesbrady.org/theories",
  "What it covers: The theories index lists open questions worked in public, with each theory's maturity state shown as prominently as its title.",
  "",
  "### Lab",
  "Source: https://www.jamesbrady.org/lab",
  "What it covers: The lab holds interactive artifacts, each one shipping with a written explanation page; an artifact without one is excluded from search engines by the loader.",
  "",
  "### Learn",
  "Source: https://www.jamesbrady.org/learn",
  "What it covers: The learn hub introduces three archived volumes — the Primer, the Manuscript and the Workshop — each kept at its original URL with a dated archive badge.",
  "",
  "### About",
  "Source: https://www.jamesbrady.org/about",
  "What it covers: James Brady operates two entities: Utlyze, the studio, and New Reward, the agency. The about page also answers how one person checks work before it ships.",
  "",
  "### Contact",
  "Source: https://www.jamesbrady.org/contact",
  "What it covers: Contact routes a qualified enquiry to James Brady through the existing lead gateway, and states plainly what makes a project a strong fit.",
  "",
  "### What I'm working on now",
  "Source: https://www.jamesbrady.org/now",
  "What it covers: James Brady is currently rebuilding jamesbrady.org from the ground up, with the content pipeline and the page skeleton landing first and the grounded Ask dock following. Alongside that, the visibility platform is running in production for client accounts, and plimsoll is being prepared for release signing and npm publication. This page is hand-edited monthly; the age indicator beside it is computed from the date the file itself carries.",
  "",
  "### The Primer",
  "Source: https://www.jamesbrady.org/primer",
  "What it covers: The Primer explains how modern coding systems fit together for a reader who does not write code: what code is, what a stack is, what an AI agent does, what a skill is, and what MCP connects. The volume is archived as written and kept at its original URL. Nothing in it has been rewritten to match the current site; the archive date says when it stopped being maintained.",
  "",
  "### The Manuscript",
  "Source: https://www.jamesbrady.org/manuscript",
  "What it covers: The Manuscript is a curated catalog of tools and MCP servers, grouped by the job each one does, with an install line and a source link for every entry. The catalog count shown anywhere on this site is computed from the catalog source at build. An earlier version of this site printed a hand-typed figure that was wrong by a factor of eight, and that class of defect is what the computed count exists to prevent.",
  "",
  "### The Workshop",
  "Source: https://www.jamesbrady.org/workshop",
  "What it covers: The Workshop is three practical guides that end in a working setup: standing up an AI agent, installing a skill, and connecting an MCP server. Each guide is written to be followed once, start to finish, rather than skimmed. The volume is archived as written and kept at its original URL, with the archive date stated on the page.",
  "",
  "### Links",
  "Source: https://www.jamesbrady.org/links",
  "What it covers: The links page collects James Brady's public profiles and project destinations in one place, kept at its original URL.",
  "",
  "### Watch",
  "Source: https://www.jamesbrady.org/watch",
  "What it covers: The watch page holds recorded walkthroughs, frozen with the archive and kept at its original URL.",
  "",
  "## Work",
  "",
  "Systems listed: 7. This count is computed from the content source, never typed.",
  "",
  "### OfOne",
  "Source: https://www.jamesbrady.org/work/ofone",
  "Kind: Products, Open source",
  "Answer capsule: OfOne is an open-source decision compiler that turns a hard question into a typed, checkable map before it writes any prose. The map holds evidence, claims, unknowns, kill tests, causal edges, options, triggers and human gates. A validator program checks the map, and only a map that passes gets rendered into an answer. When a new fact arrives, only the chain that depended on the changed fact is patched, and the system reports what it invalidated.",
  "Summary: An open-source decision compiler: a hard question becomes a typed, validated map, and the prose you read is a rendering of that map.",
  "Published 2026-08-11. Last modified 2026-08-11.",
  "Stack: Node.js, JSON Schema, Semantic graph validator, Markdown skill definition (SKILL.md), GitHub Pages, Vite, React, tRPC, Drizzle, Vercel, Railway",
  "Timeframe: 2026-05, ongoing",
  "Repository: CryptoJym/ofone-skillchain, public, MIT licensed. Stars: 0, read on 2026-08-11",
  "Measured changes:",
  "  - Predeclared benchmark run slots complete: 0 of 90 to 52 of 90. Method: Counted from batch 01 of the project's own benchmark standard, which requires at least 21 retrospective cases across six task families before any performance claim.. Timeframe: Batch 01 opened 2026-05-17, read 2026-08-11",
  "Proof:",
  "  - Repository — CryptoJym/ofone-skillchain. Method: GitHub API read, public repo. MIT licensed. Version badge 0.7.0. Last push 2026-08-01.. Captured 2026-08-11. Where: https://github.com/CryptoJym/ofone-skillchain",
  "  - Live walkthrough site. Method: HTTP GET, returned 200.. Captured 2026-08-11. Where: https://cryptojym.github.io/ofone-skillchain/",
  "  - Live product front — of1.ai. Method: HTTP GET following redirects, returned 200.. Captured 2026-08-11. Where: https://of1.ai",
  "Home proof slot: 52 of 90 predeclared benchmark slots run. Method: Counted from batch 01. The repo states in writing that the included interactive benchmark is a smoke test and establishes nothing.. State: active",
  "Live links checked:",
  "  - https://cryptojym.github.io/ofone-skillchain/ returned 200 on 2026-08-11",
  "  - https://of1.ai returned 200 on 2026-08-11",
  "Full text:",
  "The problem Ask an expert a hard question and you get an essay back. The essay reads well. You cannot check it. You cannot see which facts it rests on, how old those facts are, what would change the answer, or where a person was supposed to sign off. When the world moves, the whole essay has to be rewritten, because nobody can tell which parts still hold. What I built OfOne turns a hard question into a map before it writes a single sentence of answer. The map is made of typed objects: evidence, claims, unknowns, kill tests, causal edges, options, triggers, and human gates. A validator program checks the map. Only a map that passes gets turned into prose. The answer you read is a rendering of the map, the way a photograph is a rendering of a building. The blueprint stays attached. Two pieces ship. ofone-skillchain is the open method: the skill file, the schemas, the validator, the adapters, and a live walkthrough site. of1.ai is the product front that teaches the same method as three steps, Prism, Map, and Forge. How it works in plain words You state what is being decided, over what time, at what stakes. That is the charter. Then you list your evidence, and each piece carries its source, how fresh it is, and how reliable it is. Claims sit on top of evidence. Anything you do not know becomes a real object called an unknown, and an unknown is allowed to block the recommendation. Every strong claim has to name the result that would prove it wrong. Confidence is low, medium, or high, plus a named reason. It is never a made-up percentage. When a new fact shows up, the map does not get rewritten. The system patches only the chain of claims, options, and gates that actually depended on the fact that changed, and it reports what it invalidated. Four adapters translate the same skeleton into four working languages: strategy and operations, science and engineering, formal proof, and contested-values questions. Real problems mix these, so a map can declare a mix instead of pretending one lens fits. What is not proven The benchmark suite is a scaffold, not a result. The project's own standard requires at least 21 retrospective cases across six task families before any performance claim. Batch 01, opened 2026-05-17, records 52 of 90 predeclared run slots complete with local reviews. The repo says in writing that the included interactive benchmark is a smoke test and does not establish superiority. OfOne makes no speed or accuracy claim, and neither does this page. One excluded run is kept on purpose. A full-OfOne slot was rejected because its artifact identity was copied from the wrong case. The failed run stays in the repo as immutable evidence, and the rerun is tracked separately so history is not rewritten. [pending] Stack Node.js. JSON Schema plus a semantic graph validator. Markdown skill definition (SKILL.md). GitHub Pages for the walkthrough. Product front: Vite, React, wouter, shadcn/ui, tRPC, Drizzle, deployed on Vercel, API on Railway.",
  "",
  "### plimsoll",
  "Source: https://www.jamesbrady.org/work/plimsoll",
  "Kind: Open source, Products",
  "Answer capsule: Plimsoll is a local-first collector that ties AI coding spend to shipped outcomes, so a team can say what its tokens actually bought. The collector watches Claude Code and Codex on your own machine, records what each session cost, and joins those sessions to merged pull requests and passing checks. Content is discarded before anything reaches disk and identifying strings are hashed. The published unit is cost per merged pull request.",
  "Summary: A local-first collector that joins AI coding spend to merged pull requests, so cost per shipped outcome stops being a guess.",
  "Published 2026-08-11. Last modified 2026-08-11.",
  "Stack: TypeScript, Node 20–24, OpenTelemetry logs, traces and metrics, Local SQLite ledger (90-day retention), pnpm monorepo, macOS LaunchAgent",
  "Timeframe: 2026-06, ongoing",
  "Repository: CryptoJym/plimsoll, public, Apache-2.0 licensed. Stars: 0, read on 2026-08-11",
  "Measured changes:",
  "  - Cost of one merged pull request, measured end to end: not recorded to $48.46. Method: Published in the project README: pull request 28, merged, checks passed. One session: 41,799 input tokens, 188,834 output tokens, 30.4M cache reads. Plimsoll measuring the pull request that built Plimsoll.. Timeframe: Single session, read 2026-08-11",
  "Proof:",
  "  - Repository — CryptoJym/plimsoll. Method: GitHub API read, public repo. Apache-2.0. TypeScript. Last push 2026-07-20.. Captured 2026-08-11. Where: https://github.com/CryptoJym/plimsoll",
  "  - Project site — plimsoll.dev. Method: HTTP GET, returned 200.. Captured 2026-08-11. Where: https://plimsoll.dev",
  "  - Measured cost of PR 28. Method: Read from the published README: merged pull request, checks passed, one session, $48.46.. Captured 2026-08-11. Where: https://github.com/CryptoJym/plimsoll",
  "Home proof slot: $48.46 one merged PR, measured end to end. Method: Published in the project README for PR 28: one session, 41,799 input tokens, 188,834 output tokens, 30.4M cache reads.. State: active",
  "Live links checked:",
  "  - https://plimsoll.dev returned 200 on 2026-08-11",
  "Full text:",
  "The problem Teams spend real money on AI coding agents and cannot say what they got. Vendor dashboards stop at an org-level total. Nobody joins the spend to the thing that shipped. So the honest answer to \"what did those tokens buy us\" is a guess, and the guess is usually flattering. What I built Plimsoll is a local-first collector that watches Claude Code and Codex on your own machine, records what each session cost, and joins those sessions to shipped outcomes: merged pull requests and passing checks. Then it does the division: tokens per merged pull request, cost per validated outcome, and where the spend produced nothing. The name comes from Samuel Plimsoll, who in 1876 forced shipowners to paint a load line on every hull. Deaths from overloading fell, not because the rule was clever, but because the limit became visible to anyone standing on the dock. How it works in plain words Claude Code sends hook events. Both tools send OpenTelemetry data. The collector listens on your machine at 127.0.0.1:48271 and writes to a local SQLite file. It does not send your work anywhere. Before anything is written to disk, the collector throws away the content: prompts, model outputs, command bodies, file contents, diffs, and tool arguments. It hashes the things that identify you: emails, file paths, branch names, repository remotes. It keeps the boring parts plain: timestamps, tool names, models, token counts, costs, durations, and commit hashes. Sessions join to pull requests by matching hashes, not names. Both sides hash the same normalized inputs, so the join works while the raw strings never leave your machine. The health check is honest by design. doctor climbs four rungs, from not_installed to signal_verified, and only the top rung exits zero. A fresh install with no real token traffic fails, on purpose, instead of reporting a green light it has not earned. What is not finished Stated as unfinished in the README: background service mode for npm installs is not fitted yet, and the lifecycle command set is proofed in isolation but not released. Release signing and npm publication are tracked in issue 103. The privacy claim is testable rather than promised. The suppression rules live in packages/shared/src/policy.ts and the forbidden-field list lives in packages/shared/src/schemas.ts. A fidelity test plants sentinel commands, paths, and prompts, then fails if any of them survive to disk. [pending] Stack TypeScript. Node 20 to 24. OpenTelemetry logs, traces, and metrics. Local SQLite ledger with 90-day retention. pnpm monorepo. macOS LaunchAgent. Optional hosted sync that is off by default.",
  "",
  "### The visibility platform",
  "Source: https://www.jamesbrady.org/work/visibility-platform",
  "Kind: Products, Client work",
  "Answer capsule: The visibility platform measures how findable a business is in ordinary search and inside AI assistants, then scores it against a fixed rubric of 12 axes and 76 measures. A fixed rubric is what makes this month comparable to last month, and one business comparable to another. Every client is a tenant with walled data. Missing evidence is recorded as missing and never scored as a zero, because a report that fills gaps with zeros misleads the person paying for it.",
  "Summary: A multi-tenant platform that measures how findable a business is in search and in AI answers, and prints the evidence under every score.",
  "Published 2026-08-11. Last modified 2026-08-11.",
  "Stack: Next.js, TypeScript, Vercel, Prisma (multi-tenant schema), Clerk, Search Console + analytics sync, DataForSEO adapters, Self-hosted CI runners with a merge queue",
  "Timeframe: 2025-11, ongoing",
  "Anonymized: yes. Client name and identifying details withheld per agreement; screenshots and metrics otherwise unaltered.",
  "Measured changes:",
  "  - Measures behind one score: not recorded to 76 measures under 12 fixed axes. Method: Counted from the scorecard source of 2026-08-11. The axes are fixed on purpose: a fixed rubric is what makes two runs comparable.. Timeframe: Rubric as of 2026-08-11",
  "Proof:",
  "  - Live application. Method: HTTP GET, returned 200.. Captured 2026-08-11. Where: https://new-rewards.vercel.app",
  "  - Published method — the scorecard documentation site. Method: HTTP GET, returned 200. The underlying repository is private; the method site is public.. Captured 2026-08-11. Where: https://h3ro-dev.github.io/new-reward-seo-skills-os/",
  "  - Agency front. Method: HTTP GET, returned 200.. Captured 2026-08-11. Where: https://newreward.com",
  "Home proof slot: 76 measures under 12 fixed axes. Method: Counted from the scorecard source. Fixed rubric, so two runs stay comparable.. State: live",
  "Live links checked:",
  "  - https://new-rewards.vercel.app returned 200 on 2026-08-11",
  "  - https://newreward.com returned 200 on 2026-08-11",
  "  - https://h3ro-dev.github.io/new-reward-seo-skills-os/ returned 200 on 2026-08-11",
  "Full text:",
  "Anonymization note. Client names and identifying details are withheld per agreement. Industries are named, specific clients are not. Screenshots and metrics are otherwise unaltered. Named case studies get published only when a client gives written clearance. The problem A business used to be findable in one place: Google. Now a buyer may never see a search result. They ask an assistant, and the assistant answers from sources the business has never checked. Most owners have no way to see what those answers say about them, no way to compare themselves to a rival, and no way to tell which fix is worth doing first. What I built A multi-tenant platform that measures how findable a business is in ordinary search and inside AI assistants, scores it against a fixed rubric, turns the score into a report a non-technical owner can read, and then feeds the gaps back as work. The rubric is a 12-axis scorecard with 76 measures underneath it. The axes are fixed on purpose. A fixed rubric is what makes this month comparable to last month, and one business comparable to another. Industries served so far: medical and health services, HVAC, roofing, concrete, gutters, financial and commercial lending, custom software and IT staffing, pet breeding, background screening, promotional products, and call-center software. How it works in plain words Every client is a tenant with its own walled data. Nothing crosses between tenants. A run collects from outside first, using only what any member of the public could see, so a measurement never depends on getting access to a client's accounts. Where connections exist, the platform also reads Search Console and analytics directly. Each finding is stored with its source, the date, and the exact vantage point it was seen from, because the same page can look different to different visitors. Missing evidence is recorded as missing. It is never scored as a zero. That single rule is the difference between a report that helps and a report that misleads. The report leads with the comparison and the business conclusion. The score sits under a plain checklist and a visible formula. The technical evidence goes in an appendix, so an owner can act without reading it and a technician can check it without arguing. What is not shown here The platform repository is private, so the proof on this page is the live application, the agency front, and the published method site. [pending] [pending] [pending] Stack Next.js and TypeScript on Vercel. Prisma with a multi-tenant schema keyed by tenant and client. Clerk for authentication. Search Console and analytics sync. DataForSEO adapters for backlinks, keyword data, and assistant-mention checks. Self-hosted CI runners with required checks and a merge queue.",
  "",
  "### EEG meditation toolkit",
  "Source: https://www.jamesbrady.org/work/eeg-meditation-analysis",
  "Kind: Open source, Experiments",
  "Answer capsule: The EEG meditation toolkit is Python tooling that turns a raw consumer-headset recording into a readable account of a meditation session. Filtering removes artifacts, power is measured in each brainwave band, and a depth score from 0 to 100 rolls up with one of four labels: alert, light, moderate or deep. A synthetic data generator ships with it, so the whole pipeline runs without a headset and without handing over a personal recording.",
  "Summary: Python tooling that filters an EEG recording, measures band power, and scores meditation depth. It runs without hardware.",
  "Published 2026-08-11. Last modified 2026-08-11.",
  "Stack: Python 3.8+, NumPy, SciPy, Matplotlib",
  "Timeframe: 2025-09 to 2025-11",
  "Repository: CryptoJym/eeg-meditation-analysis, public, MIT licensed. Stars: 3, read on 2026-08-11",
  "Proof:",
  "  - Repository — CryptoJym/eeg-meditation-analysis. Method: GitHub API read, public repo. MIT licensed. Python. 3 stars. Last push 2025-11-11.. Captured 2026-08-11. Where: https://github.com/CryptoJym/eeg-meditation-analysis",
  "  - Runnable end to end without hardware. Method: Read from the repo: python generate_sample_eeg.py then python eeg_analysis.py runs the whole pipeline on synthetic data.. Captured 2026-08-11. Where: https://github.com/CryptoJym/eeg-meditation-analysis",
  "Home proof slot: 3 stars from outside this project. Method: Read from the GitHub API on 2026-08-11. Every outside star counted anywhere on this site is on this one repo.. State: dormant",
  "Full text:",
  "The problem People who meditate have almost no way to tell whether a session went deep or shallow, other than how it felt. Consumer EEG headsets record the signal, but the raw signal is noise to a human eye. The gap is not the sensor. It is the analysis in between. What I built A Python toolkit that takes an EEG recording and reports what happened during a meditation session. It filters the signal, removes artifacts, measures power in each brainwave band, and scores meditation depth from 0 to 100. It can also walk a whole session in sliding windows, so you can see where attention drifted and where it settled. It ships a synthetic data generator, so anyone can run the whole pipeline without owning a headset or handing over their own recordings. How it works in plain words Brain activity gets sorted into frequency bands. Delta is the slowest, from 0.5 to 4 cycles per second. Theta runs from 4 to 8. Alpha, Beta, and Gamma go up from there. Deep meditative states show more of the slow bands and less of the fast ones. The toolkit measures how much power sits in each band, then computes ratios between them. A higher Delta to Theta ratio points to deeper states. The Theta to Alpha ratio tracks the move from alert to meditative. It also reports spectral entropy, which is a measure of how disordered the signal is, and the dominant frequency. Those numbers roll into one score and one of four labels: alert, light, moderate, or deep. It draws the whole thing as a multi-panel chart with a spectrogram, the power spectrum, and the band distribution. Honest limits This is a signal-processing toolkit, not a clinical instrument and not a validated study. The four state labels are thresholds taken from published band conventions, and no control group was used to check them. No accuracy claim is made here. Status: dormant. The last commit was 2025-11-11, about nine months before this page was drafted. [pending] Stack Python 3.8 or newer. NumPy and SciPy for filtering and power spectral density. Matplotlib for the multi-panel plots.",
  "",
  "### seopr1.com",
  "Source: https://www.jamesbrady.org/work/seopr1",
  "Kind: Products",
  "Answer capsule: seopr1.com is a five-page marketing site for AI-search visibility, built so the site itself survives the scrutiny the service invites. Pages ship as static HTML with one framework dependency; a WebGL tuning fork tied to scroll carries the hero, and every effect has an explicit fallback. If WebGL is missing, the whole DOM experience remains and only the 3D drops. Nothing important lives inside the animation.",
  "Summary: A five-page site selling AI-search visibility, built speed-first: static pages, one dependency, and an explicit fallback for every effect.",
  "Published 2026-08-11. Last modified 2026-08-11.",
  "Stack: Astro 6, three.js r128, GSAP + ScrollTrigger, Lenis, SVG filters, Vercel",
  "Timeframe: 2026-07, ongoing",
  "Repository: CryptoJym/seopr1-site, public. Stars: 0, read on 2026-08-11",
  "Proof:",
  "  - Live site — seopr1.com. Method: HTTP GET, returned 200.. Captured 2026-08-11. Where: https://seopr1.com",
  "  - Repository — CryptoJym/seopr1-site. Method: GitHub API read, public repo. One production dependency (astro ^6.2.2). Five pages. robots.txt, sitemap.xml and an OG image ship with the site.. Captured 2026-08-11. Where: https://github.com/CryptoJym/seopr1-site",
  "Live links checked:",
  "  - https://seopr1.com returned 200 on 2026-08-11",
  "Full text:",
  "The problem A site that sells AI-search visibility has a credibility trap built into it. If the site itself is slow, invisible to crawlers, or generic, the pitch is dead on arrival. It also has a plain business job: explain a new service to professional firms who have not heard of it, and book a call. What I built A five-page site built for speed first and motion second. The hero carries a 3D tuning fork rendered in WebGL, tied to scroll. Ripple and wave layers sit behind the copy. The whole thing ships as static pages with one framework dependency, so the visual ambition does not cost load time. How it works in plain words The site is built with Astro, which sends plain HTML and adds interactivity only where it is needed. The 3D fork runs on WebGL through three.js, driven by GSAP ScrollTrigger, so the object turns as you read. The interesting part is what happens when the fancy layer is not available. If WebGL is missing, the code keeps the whole DOM experience, reveals and theme included, and drops only the 3D. On small screens the wave canvas is switched off entirely, and a legibility plate sits behind copy wherever the fork would pass under text. Nothing important lives inside the animation. Structured data describes the service in the page source, so an assistant reading the page gets the same explanation a person does. Booking runs through an embedded scheduler, so the call happens in one click instead of a form and a wait. What is not measured here Accessibility and fallback behaviour are in the source rather than asserted here: the WebGL branch has an explicit no-WebGL path, and decorative canvases carry aria-hidden. [pending] Stack Astro 6. three.js r128. GSAP with ScrollTrigger. Lenis for smooth scroll. SVG filters for ripple distortion. Deployed on Vercel. Booking through an embedded scheduler widget.",
  "",
  "### AI-readiness assessment",
  "Source: https://www.jamesbrady.org/work/ai-readiness-assessment",
  "Kind: Products, Open source",
  "Answer capsule: The AI-readiness assessment scores an organization across seven competency domains using 28 questions, and returns four views of the same result rather than a single number. Questions filter by role, so an executive, a manager, an IT lead and an HR lead each answer what they can actually judge. Four views matter because one number hides which two domains are dragging the average down. Results export as a formatted PDF or as raw JSON.",
  "Summary: An interactive assessment scoring seven AI-competency domains across 28 role-filtered questions, with four views of the same result.",
  "Published 2026-08-11. Last modified 2026-08-11.",
  "Stack: Next.js 15 App Router, TypeScript, Tailwind CSS, shadcn/ui, Framer Motion, Recharts, Vercel",
  "Timeframe: 2025-07 to 2025-08",
  "Repository: CryptoJym/ai-readiness-assessment, public, MIT licensed. Stars: 0, read on 2026-08-11",
  "Proof:",
  "  - Live assessment. Method: HTTP GET, returned 200.. Captured 2026-08-11. Where: https://ai-readiness-assessment-eight.vercel.app",
  "  - Repository — CryptoJym/ai-readiness-assessment. Method: GitHub API read, public repo. MIT licensed. Last push 2025-08-15.. Captured 2026-08-11. Where: https://github.com/CryptoJym/ai-readiness-assessment",
  "Live links checked:",
  "  - https://ai-readiness-assessment-eight.vercel.app returned 200 on 2026-08-11",
  "Full text:",
  "The problem Most organizations answer \"are we ready for AI\" with a feeling. The people who ask are usually executives, and the answer they get back is a vendor's opinion. There is no shared frame, so two departments in the same company can disagree without ever finding out why. What I built An interactive assessment that scores an organization across seven competency domains, using 28 questions, and returns charts and a downloadable report. It filters questions by role, so an executive, a manager, an IT lead, and an HR lead each answer what they can judge. How it works in plain words The seven domains are: mindset and ethics, governance and risk, opportunity discovery, workflow integration and prompting, verification and quality, execution discipline, and culture and change. You answer one domain at a time, with a progress bar showing where you are. Every domain has its own color, used consistently across every chart, so a weak area looks the same wherever it appears. At the end you get four views of the same data: a bar chart by domain, a radar chart for the overall shape, a distribution, and a maturity matrix showing where you sit on the journey. Four views matter because a single number hides which two domains are dragging the average down. Results export as a formatted PDF for sharing, or as raw JSON if you want to track scores over time rather than take a snapshot and forget it. Honest status The tool is live and working, and it has not been changed in about a year. Last commit 2025-08-15. [pending] [pending] Stack Next.js 15 with the App Router. TypeScript. Tailwind CSS. shadcn/ui components. Framer Motion. Recharts. PDF export. Deployed on Vercel.",
  "",
  "### The Of One family",
  "Source: https://www.jamesbrady.org/work/of-one-family",
  "Kind: Experiments, Products",
  "Answer capsule: The Of One family is a thesis being tested, not a finished product line: a governed set of domains and applications that each name a single company role and ask what that role looks like as one person plus AI. Two of them are live applications. The rest is staked ground: domains and landing pages that exist to find which role-shaped problem pulls interest before anything gets built. The page labels which is which, every time.",
  "Summary: A governed family of role-shaped domains for one-person businesses: two live applications, the rest deliberately staked ground.",
  "Published 2026-08-11. Last modified 2026-08-11.",
  "Stack: Next.js, Vercel, Shared component library (ofone-ui)",
  "Timeframe: 2025-06, ongoing",
  "Proof:",
  "  - Live application — financeofone.com. Method: HTTP GET, returned 200.. Captured 2026-08-11. Where: https://financeofone.com",
  "  - Live application — vcofone.ai. Method: HTTP GET, returned 200. Note: vcofone.com resolves but serves nothing; the live domain is the .ai.. Captured 2026-08-11. Where: https://vcofone.ai",
  "  - Landing page — businessofone.ai. Method: HTTP GET, returned 200.. Captured 2026-08-11. Where: https://businessofone.ai",
  "Live links checked:",
  "  - https://businessofone.ai returned 200 on 2026-08-11",
  "  - https://financeofone.com returned 200 on 2026-08-11",
  "  - https://vcofone.ai returned 200 on 2026-08-11",
  "Full text:",
  "Read this first. This entry is a thesis being tested, not a finished product line. Most of what is described below is staked ground: a registered domain and a landing page, nothing more. A small number are real, working applications. The page labels which is which, every time. Ideation repositories are not counted as products. The problem Software for a one-person business is usually shrunken software for a big company. The work a solo operator actually has to do is different in kind, not just in size. One person is the CEO, the finance function, the legal review, and the marketing department in the same afternoon. The thesis is that each of those jobs deserves its own tool, built for one person, rather than a seat in a suite built for fifty. What I built A governed family of domains and applications under the \"of One\" idea. Each one names a single company role and asks what that role looks like when the whole department is one person plus AI. Two things are true at once, and the page says both. First, the real ones. financeofone.com and vcofone.ai are live applications, not brochures. They are the ones worth judging. Second, the staked ground. The rest of the family is domains and landing pages. They exist to test which role-shaped problem pulls the most interest before anything gets built. That is a legitimate way to find demand. It is not the same as shipping a product, and calling it shipping would be a lie. How it works in plain words The family runs on one rule: a domain does not become a product until someone shows up wanting it. Landing pages carry the promise. Traffic and signups say which promise is real. Only then does a build start. That order is deliberate, and it is why the count of domains is much larger than the count of applications. Shared UI components live in one place, ofone-ui, so a build that graduates does not start from an empty folder. What this page will not print The family-wide counts of governed domains and live landing pages are not shown here. They come from a checked domain list that has to be re-checked at build with a date on it, and that check is not wired up yet. A count with no date is exactly the kind of number this site exists to avoid. [pending] [pending] Stack Mostly Next.js on Vercel for the landing pages. Shared component library ofone-ui. Domain and provider mapping tracked in a per-family audit document.",
  "",
  "## Theories",
  "",
  "Theories listed: 7. A theory at \"named only\" maturity is deliberately absent from this pack and from every discovery surface.",
  "",
  "### Why do questions have geometry?",
  "Source: https://www.jamesbrady.org/theories/universal-question-geometry",
  "Theory name: Universal Question Geometry",
  "Maturity: Developed",
  "Claim: A question is an operator on a belief state, so a set of candidate questions has a computable value landscape and the next question can be selected rather than guessed.",
  "Abstract: Universal Question Geometry treats inquiry as a search over a value landscape of questions rather than a list to be worked through, and it refuses to stop while a positive-expected-value question remains open.",
  "In one line: Questions have shape, and the shape predicts what an answer can reach. A map of how questions sit next to each other, and why some open doors that others structurally cannot.",
  "Answer capsule: Universal Question Geometry treats a question as an operation that changes the state of knowledge, which means questions can be ranked and scored before any of them are asked. The method keeps a running picture of the current state of knowledge, estimates how much each candidate question would move that picture, and selects the next question from the top of that ranking. Stopping is not allowed on the feeling of being finished; a stop attempt is rejected while a question with positive expected value is still open.",
  "Summary: Treating a question as an operator on a belief state, so the next question can be ranked and selected instead of guessed.",
  "Published 2026-05-17. Last modified 2026-08-11.",
  "Artifact: Read the walkthrough at https://cryptojym.github.io/ofone-skillchain/",
  "History:",
  "  - 2026-05-17: sketched. Benchmark batch 01 opened with 90 predeclared run slots.",
  "  - 2026-08-01: developed. Engine, protocol, enforcement layer and documentation all run; evidence still open.",
  "Proof:",
  "  - QUESTION_GEOMETRY.md in CryptoJym/ofone-skillchain. Method: GitHub API read of the public repository, 2026-08-11.. Captured 2026-08-11. Where: https://github.com/CryptoJym/ofone-skillchain",
  "  - The walkthrough site. Method: HTTP GET, returned 200.. Captured 2026-08-11. Where: https://cryptojym.github.io/ofone-skillchain/",
  "Full text:",
  "Most inquiry runs on habit. Someone asks what comes to mind, gets an answer, asks the next thing that comes to mind, and stops when the list of questions runs out or the clock does. The order is accidental. The stopping point is a mood. Universal Question Geometry starts from a different claim: questions have shape. A question is not a request for a fact. It is an operator that moves a belief state from one position to another. Some moves are large and some are tiny. Others open doors that later questions can walk through, which means their real value is not in their own answer but in what they unlock. If that is true, then a set of candidate questions has a landscape, with peaks, valleys, and a frontier of choices where you cannot improve one thing without giving up another. The implementation makes that landscape computable. It ranks candidate questions over the current state, records the peaks, the valleys and the frontier, and re-ranks when an answer comes back and updates the beliefs and the causal structure underneath them. Three rules do most of the work Answers are qualified before they count. A challenge pass is not complete because someone marked it complete. It is complete when the answers meet the conditions. Provenance is chained. Every answer event is hashed with SHA-256 and linked to the one before it, so a state that was quietly edited after the fact does not pass verification. Depth is typed, not counted. The familiar \"five whys\" rule stops at five because five is a memorable number. Here, the traversal continues by the type of thing you are standing on. You stop when you reach bedrock: a primary source, a named mechanism, or a human ruling. You do not stop when you get tired. Stopping has guards A stop request is checked against residual expected value of information, decision robustness, whether a question was actually selected by the runtime, and whether any positive-value question remains. A rejected stop exits with code 2 and hands back the next required question. That is the part that changes behaviour most: a person who wants to be finished cannot simply declare it, because the runtime is holding an open question with a positive score and will say so. Two more things exist because inquiry gets stuck rather than wrong. Stall detection notices when the loop is circling and switches operator. And a configured safety boundary sends the whole thing to a human before it can run away. What is proven, and what is not The engine, the protocol, the enforcement layer, and the documentation all exist and run. The evidence does not exist yet, and this page is not going to imply otherwise. The project's own benchmark standard demands at least 21 retrospective cases across six task families before any performance claim, and batch 01 stands at 52 of 90 predeclared run slots. The repository states in writing that the included benchmark is a smoke test and establishes nothing. So the honest state of this theory is: developed, and deliberately unproven. The machinery is real and the discipline around it is real. The result is still outstanding. That gap is stated here rather than papered over, because a theory page exists to be checked. A reader who wants to disagree with this one has everything needed to do it: the runnable loop, the standard it will be judged against, and the count of how far the evidence has got. Artifacts - QUESTION_GEOMETRY.md and docs/question-geometry-engine.md in github.com/CryptoJym/ofone-skillchain - The runnable loop: node scripts/ofone-question-loop.mjs - The walkthrough site: cryptojym.github.io/ofone-skillchain - Related case study: OfOne",
  "",
  "### Why should a useful-looking finding get more scrutiny, not less?",
  "Source: https://www.jamesbrady.org/theories/question-answer-dynamics",
  "Theory name: Question–Answer Dynamics",
  "Maturity: Developed",
  "Claim: Scrutiny should scale with how convenient a finding is, because a finding that flatters the plan attracts fewer hard questions than one that contradicts it.",
  "Abstract: Question-Answer Dynamics runs a fixed battery of questions on every finding before that finding is acted on, and refuses to end research on satisfaction rather than on a written stop reason.",
  "In one line: What an answer does to the next question. The loop, measured: most of the value in a conversation lives in how the second question moved.",
  "Answer capsule: Question-Answer Dynamics is a rule for interrogating every finding before that finding is acted on, and the central claim is that scrutiny should scale with how convenient a finding is. A finding that contradicts the plan already attracts hard questions; a finding that flatters the plan does not, which is exactly why it slips through unchecked. The method fixes this by running a fixed battery of questions on every finding and by refusing to stop research on satisfaction.",
  "Summary: A fixed battery of questions run on every research finding, because convenient findings are the ones that escape scrutiny.",
  "Published 2026-06-02. Last modified 2026-08-11.",
  "History:",
  "  - 2026-06-02: sketched. Two founding cases, both real engagements.",
  "  - 2026-08-11: developed. Written as an executable skill and running on live competitive-intelligence work.",
  "Proof:",
  "  - The method as applied — the visibility platform case study. Method: The two founding cases are real engagements, described by industry only. The engagement record is internal; the applied method is described in the linked case study.. Captured 2026-08-11. Where: artifact /work/visibility-platform (redacted)",
  "Full text:",
  "Two failure modes started this. Failure mode one: gift acceptance On one competitive-intelligence engagement, for a custom software and IT staffing firm, the research turned up something convenient: a rival's site appeared to be blocked from indexing. It was banked immediately as leverage. Nobody asked the boring questions. When those questions were finally asked, the finding reversed. When did it start? Well before the rival's repositioning, so it was not strategy. Was it intentional? No, it was a hosting default nobody managed. Was it total? No, it was keyed to specific visitors, so real search crawlers passed through. Could it be undone? Yes, with one toggle. The convenient reading said \"exploit their wall\". The interrogated reading said \"fix your own foundation, and treat their wall as a temporary bonus that may vanish tomorrow\". Two opposite plans from one fact. Failure mode two: the checklist stop An audit finished its task list, declared completion, and was asked one more question: is there more to learn here? That question turned one instance into a class, and four more gaps came out. The task list had been a fine list. It was simply not a reason to stop. So the method has two halves The battery, run on every finding. Is it real, and was it measured or inferred? When did it start, and which way is it moving? Why would a rational actor produce this state, on purpose, by accident, or through neglect? What else is on this same surface? How does it read from four other viewpoints? What would make this misleading? Where does it lead next? Unknown is a permitted answer. Skipping the question is not permitted. The scheduler. Every interrogated finding ends with either a list of next questions or a written reason for stopping, and never with neither. All open next-questions from all findings go into one queue, ranked by value divided by cost. The top one gets pulled, the answer comes back, and it re-enters the battery. That queue is the research plan. It is not written on day one; it regrows from every answer. When research ends Research ends when every finding has been interrogated, every remaining question has a written stop reason, no contradictions are left unresolved, and beliefs are strong enough for the use they are being put to. It does not end when the researcher feels done. The asymmetry is what the battery is for. A finding that contradicts the plan gets challenged automatically, because someone has an interest in challenging it. A finding that flatters the plan has no natural opponent in the room. The battery is that opponent, applied evenly, so the level of scrutiny stops depending on whether anyone in the room wanted the answer. There is a second-order effect worth naming. Once every finding ends in either questions or a written stop reason, the shape of the research changes. A plan written on day one is a guess about what will be worth knowing; a queue that regrows from every answer is a record of what turned out to be worth knowing. The two produce very different documents at the end, and only one of them can be audited afterwards by someone who was not there. The battery also survives being applied to itself, which is the test I care about most. Ask of the method: is it real, or inferred? It is inferred: two cases is an origin story, not evidence. Which way is it moving? Toward more use, not more proof. What would make it misleading? A team that runs the battery as a form to fill in rather than as questions to answer would produce the paperwork of scrutiny with none of the substance, and the logs would look identical. Where this stands Developed and in daily use. The method is written as an executable skill and runs on live competitive-intelligence work. Its two founding cases are real engagements, described here by industry only. The stop and continue decisions are logged so they can be scored over time, but that scoring has not been published. The claim on this page is that the method is in use, not that it has been proven to produce better research. Artifacts - The skill definition, installed and running in the operating environment - Related case study: The visibility platform [pending]",
  "",
  "### Can one person run a software team by splitting judgment from building?",
  "Source: https://www.jamesbrady.org/theories/architect-loop",
  "Theory name: The Architect Loop",
  "Maturity: Developed",
  "Claim: A model that writes code and also grades that code will grade it kindly, so the grading authority must sit outside the building context and the standard must be frozen before work starts.",
  "Abstract: The Architect Loop separates judgment from building, freezes the gates before work starts, and hands the final verdict to a judge with no memory of the build conversation.",
  "In one line: One model holds judgment, a separate set of models does all the building, and a git repository is the only shared memory. A fork of Dan McInerney's project, hardened and run daily.",
  "Answer capsule: The Architect Loop is a working arrangement in which one AI model does judgment only and a separate set of AI models does all the building, with a git repository as the only shared memory. Judgment means arbitration, verdicts against frozen gates, splitting work into lanes, and deciding whether to continue or kill. Building means writing code in isolated worktrees, with no authority to decide whether its own work passed.",
  "Summary: One model judges, others build, and the repository is the only memory. A hardened fork of Dan McInerney's architect-loop.",
  "Published 2026-04-20. Last modified 2026-08-11.",
  "Artifact: Upstream project at https://github.com/DanMcInerney/architect-loop",
  "History:",
  "  - 2026-04-20: sketched. Fork taken; local hardening begins.",
  "  - 2026-08-11: developed. Two full delivery cycles run end to end; local v2.4 pass fixed five audit findings.",
  "Proof:",
  "  - Upstream project — DanMcInerney/architect-loop. Method: The original design is Dan McInerney's. This entry describes a fork, hardened locally.. Captured 2026-08-11. Where: https://github.com/DanMcInerney/architect-loop",
  "Full text:",
  "The separation is the whole idea. A model that writes code and also grades that code will grade it kindly. Not from dishonesty, but because the same context that produced the work produces the standard. So the loop puts a wall in the middle. One model holds judgment. One to four builders run in parallel, each in its own isolated git worktree. They never share a directory, because parallel agents in one directory tidy up after each other and destroy each other's work. The repository is the only memory The memory is not chat history and not a scratch folder. It is a handoff file, a gates directory, and a lanes directory. Anything not written to the repository did not happen. That rule sounds bureaucratic until the first time a lane dies mid-run and everything it \"knew\" turns out to have been in a conversation nobody can replay. Gates are frozen before the work starts Most systems get this wrong. If the test that decides \"done\" can be edited by the thing being tested, the test decides nothing. So the gate has a tamper perimeter, and it covers more than the gate file: it includes the validators, the test files, and the script entries the gate command depends on. After the run, the loop diffs that whole set. A fix that touched the checker has to be re-verified against a known-bad input before it counts. The failure this prevents is specific and common: a guard gets broken by the diff that was supposed to satisfy it, someone narrows the guard so the run goes green, and the narrowed guard still looks like coverage from the outside. Disagreement stops the run before code If the plan and the request materially disagree, the run ends as blocked rather than proceeding on a guess. A blocked run is cheap. A run that guessed at the intent and built the wrong thing correctly is expensive. The verdict comes from a fresh judge The final verdict is given by a judge with no memory of the build conversation, and that judge is handed pointers only: the handoff file, the gates, and the frozen commit, without the story of how the work went. A judge who watched the struggle grades the struggle. This is the same principle as the wall in the middle, applied at the end instead of the beginning. Anyone who has watched a difficult piece of work come together starts to price in the difficulty, and a verdict that prices in difficulty is no longer a verdict about the artifact. Handing over pointers rather than a narrative is not a slight against the builders. It is the only way the grade means what it says. What the loop costs Honesty about the price matters as much as the design. Isolated worktrees mean more disk and slower setup. Frozen gates mean a mid-run realization that the gate was wrong becomes a stop-and-restart rather than a quiet edit. Writing everything to the repository is slower than remembering it. Each of those costs is real, and each is the direct price of the property it buys. The trade is worth taking when the work is going to be judged by someone who was not in the room: a client, a future maintainer, or the person you will be in three months. It is probably not worth taking for a throwaway script. Attribution, stated plainly The Architect Loop is not mine. It is a fork of DanMcInerney/architect-loop, heavily customized, run daily, and hardened locally. Five audit findings were fixed in a local v2.4 pass, and one of those fixes was offered back upstream as a pull request. What I contribute is the hardening and the operating discipline, not the original design. I say that here rather than in a footnote because a portfolio that quietly absorbs other people's work is exactly the kind of thing this site is supposed to be the opposite of. Where this stands Developed and field-proven, on a fork I do not own. Two full delivery cycles have run end to end under it, in client engagements described here by industry only: pet breeding, and financial and commercial lending. The upstream project has since been rebuilt into a different architecture, and my install deliberately stays on the older shape. Artifacts - Upstream project: github.com/DanMcInerney/architect-loop - Related theory: Function-First Orchestration [pending]",
  "",
  "### Do language models share a hidden vocabulary for relational states?",
  "Source: https://www.jamesbrady.org/theories/latent-emotions",
  "Theory name: Latent Emotions in LLMs",
  "Maturity: Sketched, paused",
  "Claim: Different large language models converge on closely similar vocabulary for unnamed relational states, which may indicate shared latent structure rather than shared training vocabulary.",
  "Abstract: Latent Emotions records an observed convergence in how different models describe unnamed relational states, and states plainly that no study has been run to distinguish shared structure from coincidence in training data.",
  "In one line: Different models reach for closely similar words when describing certain relational states. That might point to shared structure underneath, or to nothing. The work is parked, and it says so.",
  "Answer capsule: Latent Emotions is a personal, unfinished observation that different large language models reach for closely similar words when describing certain relational states, which may point to shared structure underneath rather than shared training vocabulary. No claim of proof is made here, and no formal study exists. The work is paused, and the page says so instead of dressing an observation up as a programme.",
  "Summary: An unfinished observation that different models converge on similar words for unnamed relational states. Paused, with no claim of proof.",
  "Published 2026-03-14. Last modified 2026-08-11.",
  "Artifact: Open the demo at /lab",
  "History:",
  "  - 2026-03-14: sketched. Observations recorded; six-dimension working model built in conversation.",
  "  - 2026-08-11: paused. Not carried forward. Demo still runs.",
  "Proof:",
  "  - The manifold demo. Method: A lens for looking at the idea, not evidence for it. Stated as such on the demo page.. Captured 2026-08-11. Where: artifact /lab",
  "Full text:",
  "I want to be clear about what this is before I describe it. These are my own observations and my own internal thinking. They are not formal claims. There is not really any credibility to validate them yet. I am putting them here because they are interesting, and because they might yield something later, not because I think I have shown anything. Here is what I noticed. As I talked with different language models, across different vendors, I kept seeing the same vocabulary come back for specific relational states. Not common words. Particular ones, for states I would argue are nonverbal. The states themselves do not have obvious names, and yet different models reached for overlapping language when they tried to describe them. That convergence is what caught me. If separate models trained by separate companies describe an unnamed state with the same words, one explanation is coincidence in the training data. Another is that there is some shared latent structure being described. I do not know which. I have not run the work that would tell them apart. To have something to look at, I built a six-dimension model: energy, valence, complexity, novelty, introspection, and focus. Those six became the axes of a visual demo, where a conversation moves through a space instead of down a page. I should say how that model was made. I arrived at those six dimensions in conversation with a language model, together, not by deriving them from anything. I do not think it is a complete model. It was a way to view the idea. It was never meant to prove the idea. Since I started this, related work has appeared from other people. That came out after I began. I am not making a priority claim about it, and I do not think one would matter. I note the timing only because someone will ask. Where this stands I stopped. I have not carried the observations forward, and it is more of a stagnant project than an active one right now. It is here because it is honest to show the unfinished things too. Sketched, and paused. What exists is a set of observations, a six-dimension working model built in conversation, and a visual demo. There is no formal write-up, no validation design, and no result. The pause was a choice. Artifacts - The manifold demo in the lab, presented as a lens for looking at the idea, not as evidence for it [pending] [pending]",
  "",
  "### What is a five-layer operating system for an agent-run business?",
  "Source: https://www.jamesbrady.org/theories/the-paper",
  "Theory name: THE PAPER",
  "Maturity: Sketched",
  "Claim: A business run mostly by agents needs its layers gated bottom-up, because execution that runs ahead of the plan that authorizes it produces confident work against an unverified truth.",
  "Abstract: THE PAPER specifies five gated layers (business truth, intelligence, strategy, execution and visibility measurement) where each layer may act only on what the layer beneath it has established.",
  "In one line: A specification for running a business where AI agents do most of the labour, in five gated layers. The document itself stays private; this page introduces the idea and links nothing.",
  "Answer capsule: THE PAPER is a single working document that specifies a five-layer operating system for running a business where AI agents do most of the labour. The five layers are business truth, competitive monitoring and recommendation, strategy, execution, and visibility measurement, each one gated by the layer beneath it. The document is a specification under active revision, not a published theory, and this page introduces it without reproducing it.",
  "Summary: An introduction to a private specification for a five-layer, gated operating system for an agent-run business.",
  "Published 2026-07-05. Last modified 2026-08-11.",
  "History:",
  "  - 2026-07-05: sketched. Revision R5. Sections 4 onward unreviewed.",
  "  - 2026-08-11: sketched. Introduction-only page per owner ruling 2026-08-11 (SITE-BRIEF decisions log); the document itself stays private.",
  "Proof:",
  "  - The specification document. Method: Measured locally on 2026-08-11: Revision R5, dated 2026-07-05. The document is private by standing rule and is not linked from this site.. Captured 2026-08-11. Where: artifact private (redacted)",
  "Full text:",
  "This page introduces the document. It does not reproduce it, and it does not link it. The document is private by a standing rule, and the rule is older than this website. The idea it specifies is a stack. Each layer only gets to act on what the layer below it has established. Layer 1, business truth. What the company actually sells, at what price, to whom, with what economics. Captured once, at onboarding, and treated as the cornerstone. Everything above it is wrong if this is wrong. Layer 2, intelligence. Split in two on purpose. Layer 2a records facts about competitors, continuously, and only facts. Layer 2b applies judgment on top of those facts and proposes moves. Keeping observation separate from opinion is what stops a guess from hardening into a fact three steps later. Layer 3, strategy. A versioned war plan derived from truth and intelligence. Every version has to carry its reasoning and the alternatives it rejected, so a future reader can see what was considered and not just what was chosen. Layer 4, execution. The agent labour. Content, site, brand, go-to-market. Gated, so execution cannot run ahead of the plan that authorizes it. Layer 5, visibility measurement. Search and AI-answer scanning. The document is firm that this is one instrument, not the whole system. That matters because measurement is the easiest layer to build and the most tempting to mistake for strategy. What makes the document itself unusual Every load-bearing claim carries exactly one tag: locked, resolved, decision needed, assumption, unverified, or verified with an evidence path. You can strike any single line and immediately see what it takes down with it. Decisions sit at the top of each section, mechanics below, because decisions are what a reader is most likely to change. Where this stands Revision R5, dated 2026-07-05. Sections 4 onward have not been reviewed. The decision register carries open items rated high, and building against an open decision is not permitted. On this site's own ladder the page is sketched, not developed, and the reason is a rule rather than a judgement: a theory counts as developed here only once its full text is published as static HTML on its own page. That has not happened and is not going to happen while the document stays private. Calling it developed on the strength of a private file would be exactly the kind of unearned claim the rest of this site is built to avoid. Artifacts None published. The document is not linked.",
  "",
  "### What is a style rule a program can check?",
  "Source: https://www.jamesbrady.org/theories/movement-economy",
  "Theory name: Movement Economy",
  "Maturity: Sketched",
  "Claim: A writing rule enforced by a program on structured objects removes decoration more reliably than the same rule applied by taste to prose.",
  "Abstract: Movement Economy declares ten jobs a unit of analysis may do, requires every emitted unit to name its job, and deletes anything that cannot.",
  "In one line: Every sentence in a piece of analysis must do one of ten declared jobs or be deleted. Enforced on map objects inside OfOne rather than applied by taste to prose.",
  "Answer capsule: Movement Economy is a rule that every sentence in a piece of analysis must do one of ten declared jobs or be deleted. The ten jobs are: bound the question, ground it in evidence, make a claim, link two things, state a test, propose a move, evaluate options, warn, set a trigger, and gate a decision. Anything that does none of these is decoration, and decoration is removed.",
  "Summary: Ten declared jobs a unit of analysis may do. Anything that does none of them is decoration, and gets deleted.",
  "Published 2026-06-18. Last modified 2026-08-11.",
  "Artifact: Rule 8 in the repo at https://github.com/CryptoJym/ofone-skillchain",
  "History:",
  "  - 2026-06-18: sketched. Named, defined, and enforced as rule 8 of the OfOne compiler.",
  "Proof:",
  "  - Rule 8 in CryptoJym/ofone-skillchain. Method: Read from the public README section \"The rules that keep it honest\", 2026-08-11.. Captured 2026-08-11. Where: https://github.com/CryptoJym/ofone-skillchain",
  "Full text:",
  "Analysis bloats for a reason. Writing that sounds thoughtful gets rewarded. Framing, throat-clearing, restatement, and hedging all read as care. None of them change what a reader can do. Movement Economy makes that testable. Ten jobs are declared up front. Every emitted piece has to name the job it does. If it cannot name one, it goes. The effect is not shorter writing for its own sake. Everything left standing moves the decision somewhere. A reader can point at any sentence and ask which of the ten it is doing, and there is an answer or there is a deletion. The rule lives inside OfOne, where it is enforced on the map objects rather than applied by taste to prose. That is the part worth stealing: a style rule that a program can check is a different kind of rule from a style rule you have to remember. Where this stands Sketched. Named, defined, and enforced in code as rule 8 of the OfOne compiler. No standalone write-up exists yet, and no measurement of its effect on real documents. Until that measurement exists, the honest claim is that the rule is enforceable, not that enforcing it improves anything. Artifacts - Rule 8 in github.com/CryptoJym/ofone-skillchain, under \"The rules that keep it honest\" - Related theory: Universal Question Geometry",
  "",
  "### Should proof of function come before proof of thoroughness?",
  "Source: https://www.jamesbrady.org/theories/function-first-orchestration",
  "Theory name: Function-First Orchestration",
  "Maturity: Sketched",
  "Claim: Deferring broad test coverage in favour of one honest happy path plus mandatory refusal tests ships more working software per hour than a speculative test matrix.",
  "Abstract: Function-First Orchestration puts proof of function ahead of proof of thoroughness, keeps refusal tests mandatory, and requires every deferral to be written down rather than felt.",
  "In one line: Ship one honest happy-path test plus the refusals that protect money, custody and truth. Defer the rest deliberately, in writing, rather than skipping it.",
  "Answer capsule: Function-First Orchestration is an operating rule that puts proof of function ahead of proof of thoroughness. Under the rule, a piece of work ships with one honest happy-path test plus the specific refusals that protect money, custody, and truth, and nothing else. Broader test coverage is deliberately deferred rather than skipped. Each deferral is written into a parking file, so “later” becomes a concrete list entry instead of a vague intention.",
  "Summary: Prove function first: one honest happy path plus mandatory refusal tests, with every deferral written down.",
  "Published 2026-07-28. Last modified 2026-08-11.",
  "History:",
  "  - 2026-07-28: sketched. Named as a standing operating rule after test batteries outgrew the features they tested.",
  "Proof:",
  "  - Applied practice — the Architect Loop. Method: The rule governs lane briefs and gate scope in the loop described in the linked theory. No published measurement of its effect exists yet.. Captured 2026-08-11. Where: artifact /theories/architect-loop",
  "Full text:",
  "The rule came out of watching build waves produce test batteries larger than the features they tested. The tests were not wrong. They were early. Every hour spent on a speculative test matrix was an hour not spent finding out whether the thing worked at all. So the standing rule is: great is the enemy of good. Prove function. Refine later. Two things keep this from becoming an excuse for sloppiness. First, the refusals are not optional. A test that proves the system says no, correctly, when money moves, when custody changes, or when a truth claim is being made, is function-proof, not polish. Those tests ship in the first pass, every time. Second, the deferral is written down. \"Refine later\" only works if later is a real entry on a list, not a feeling. Improvements go into a parking file instead of the current wave, and the current wave's scope is frozen and shrink-only. There is a matching rule for the agents doing the work: give each one a narrow lane and all the surrounding context. Narrow, because a broad brief invites design beyond the ask. All the context, because an agent forced to re-derive a settled decision will sometimes derive a different one. Where this stands Sketched. A standing operating rule with a clear origin and daily application. No measurement has been published on whether it produced more shipped work or more defects, and that measurement is the obvious next step. Until it exists, this page claims a practice, not a result. Artifacts - Related theory: The Architect Loop [pending]",
  "",
  "## Lab",
  "",
  "### The emotional manifold",
  "Source: https://www.jamesbrady.org/lab",
  "State: Paused (paused)",
  "Written explanation: /theories/latent-emotions",
  "Answer capsule: The emotional manifold is a visual demo that moves a conversation through a six-axis space (energy, valence, complexity, novelty, introspection and focus) instead of down a page. The six axes were arrived at in conversation with a language model rather than derived from anything, so the demo is a lens for looking at an idea and not evidence for it. The theory behind it is paused, and the demo is labelled accordingly.",
  "Summary: A visual demo that moves a conversation through a six-axis space. It is a lens for an idea, not evidence for it.",
  "Published 2026-03-14. Last modified 2026-08-11.",
  "Proof:",
  "  - The theory this demo illustrates. Method: The written explanation page required of every lab artifact.. Captured 2026-08-11. Where: artifact /theories/latent-emotions",
  "Full text:",
  "A conversation gets plotted as a path through six dimensions: energy, valence, complexity, novelty, introspection and focus. The demo exists to make an idea lookable-at. It is not a measurement instrument, it does not validate anything, and the theory it belongs to is paused. Read the written explanation before drawing a conclusion from anything you see move. The hardening this artifact still needs is listed on the theory page: per-session state instead of the module-level state the original shared across visitors, its own rate budget, and framing that is scoped to what the demo actually shows.",
  "",
  "## Learn: the archived volumes",
  "",
  "### The Primer",
  "Source: https://www.jamesbrady.org/primer",
  "Archived 2026-08-11. Kept at its original URL.",
  "Answer capsule: The Primer explains how modern coding systems fit together for a reader who does not write code: what code is, what a stack is, what an AI agent does, what a skill is, and what MCP connects. The volume is archived as written and kept at its original URL. Nothing in it has been rewritten to match the current site; the archive date says when it stopped being maintained.",
  "Summary: Code, the stack, AI agents, skills and MCP, explained for humans. Archived, kept at its original URL.",
  "Published 2026-02-01. Last modified 2026-08-11.",
  "Full text:",
  "Start here if the vocabulary is the obstacle. The Primer walks from \"what is code\" to \"what is an agent\" without assuming a background, and it is the shortest path into the other two volumes.",
  "",
  "### The Manuscript",
  "Source: https://www.jamesbrady.org/manuscript",
  "Archived 2026-08-11. Kept at its original URL.",
  "Answer capsule: The Manuscript is a curated catalog of tools and MCP servers, grouped by the job each one does, with an install line and a source link for every entry. The catalog count shown anywhere on this site is computed from the catalog source at build. An earlier version of this site printed a hand-typed figure that was wrong by a factor of eight, and that class of defect is what the computed count exists to prevent.",
  "Summary: A curated catalog of tools and MCP servers with install lines and sources. Archived, kept at its original URL.",
  "Published 2026-02-15. Last modified 2026-08-11.",
  "Full text:",
  "The catalog is a shelf, not a ranking. Each entry names what the tool does, how to install it, and where the source lives, so the reader can check it rather than take the recommendation.",
  "",
  "### The Workshop",
  "Source: https://www.jamesbrady.org/workshop",
  "Archived 2026-08-11. Kept at its original URL.",
  "Answer capsule: The Workshop is three practical guides that end in a working setup: standing up an AI agent, installing a skill, and connecting an MCP server. Each guide is written to be followed once, start to finish, rather than skimmed. The volume is archived as written and kept at its original URL, with the archive date stated on the page.",
  "Summary: Three practical guides: set up an AI agent, install skills, connect MCP servers. Archived, kept at its original URL.",
  "Published 2026-03-01. Last modified 2026-08-11.",
  "Full text:",
  "Three guides that end with something running on your own machine. Follow one all the way through before starting the next.",
  "",
  "## Now",
  "",
  "### What I'm working on now",
  "Source: https://www.jamesbrady.org/now",
  "Updated 2026-08-11. Say the update date rather than \"recently\".",
  "Answer capsule: James Brady is currently rebuilding jamesbrady.org from the ground up, with the content pipeline and the page skeleton landing first and the grounded Ask dock following. Alongside that, the visibility platform is running in production for client accounts, and plimsoll is being prepared for release signing and npm publication. This page is hand-edited monthly; the age indicator beside it is computed from the date the file itself carries.",
  "Summary: Hand-edited monthly: the site rebuild, the visibility platform in production, and plimsoll heading toward release.",
  "Published 2026-08-11. Last modified 2026-08-11.",
  "Full text:",
  "Rebuilding this site The site you are reading is being rebuilt from the ground up. Wave one is the foundation: a typed content source that every page, feed and machine-readable file reads from, the design system, and the page skeleton. The grounded Ask dock comes after, and until it does the dock states its terms and offers email instead of pretending to answer. In production The visibility platform is running for client accounts, measuring how findable a business is in search and inside AI assistants. Client work stays anonymized by default here; industries are named, companies are not. Heading toward release plimsoll, the collector that ties AI coding spend to merged pull requests, has release signing and npm publication outstanding. Background service mode for npm installs is not fitted yet, and the README says so. Open on my desk The largest gap on this site is the human story on the about page, and it is mine to write. Several pages carry marked questions that only I can answer; they are shown on the page rather than filled in with something plausible.",
  "",
  "## Reaching James",
  "",
  "### How a visitor reaches James",
  "Source: https://www.jamesbrady.org/contact",
  "What it covers: Contact routes a qualified enquiry to James Brady through the existing lead gateway, and states plainly what makes a project a strong fit.",
  "Email: james@utlyze.com.",
  "When a visitor wants to work with James, get in touch, hire him, or send a message, answer with a reach_james block. Never collect a name, an email address, or any other personal detail in your own text: the block renders a form that does that, with consent.",
  "",
].join("\n");
